### PR TITLE
Remove custom range fixers

### LINKED ISSUE #268: Underline mispositioned when attribute name matches unused import
```
$ apm list | grep linter-flake8
├── linter-flake8@2.0.2

$ flake8 --version
3.0.4 (pyflakes: 1.2.3, mccabe: 0.5.2, pycodestyle: 2.0.0) CPython 3.5.1 on Darwin

$ cat linter_flake8_test.py

 import uuid
 import foo

 bar = foo.get_bar()
 baz = foo.do_something(bar.uuid)
```

underline_mispositioned
[flake8.out.txt](https://github.com/AtomLinter/linter-flake8/files/556120/flake8.out.txt)

### LINKED ISSUE #295: Atom blocked editing files with plenty of errors
I'm working on a new project with some old and no-stylish code and have lots of files with plenty of errors. Whenever I start to edit one of those files (i.e: one with ~400 errors) atom editor freezes for 5 or 6 seconds.

It is not a memory or resources problem. I have 16GB of RAM and a i5 5th generation with 4 cores.

I tried disabling other linters i have installed before (eslint, pep8) but it keep freezing every time i edit the file. I also try to disable linting automatically every 300ms and just lint whenever i save the file. With this latest configuration, i could edit the file without problem but then when i save it had the same problem again.

Watching processes with htop let me see that one atom process was consuming 100% of one core.

Is there anything i'm missing or is a known problem with the linter? Maybe it would be good to set by configuration a maximum errors to be shown. So whenever a file reach that quantity of errors the linter stop searching for problems.

### PR DESCRIPTION
**Pull request by Arcanemagus**
These custom range fixers have been nothing but problems since they were first introduced, and are better fixed in the source programs in the first place.

Interested parties can track these efforts at the following locations:

* The `C901` issue has been reported as https://github.com/PyCQA/mccabe/issues/43
* `H201` marking the `:` can be tracked here: https://bugs.launchpad.net/hacking/+bug/1648585
* `H501` positions turned out to be just plain wrong for all indented code, reported here: https://bugs.launchpad.net/hacking/+bug/1648594

Fixes #295.
Closes #268.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
`F401` I'm unsure what to do about, there are several _related_ issues in the Pyflakes [bug tracker](https://bugs.launchpad.net/pyflakes) already, but none that seem to be exactly what was being corrected here. Pyflakes currently seems to just mark the start of the `import`, whether that is `import` or `from`. I'm not sure whether that's just "good enough" or if something should be reported about this.

**Comment by pferreir** [comment]
That seems to work better than the current version (no more slowdowns such as the ones reported in #295).

**Comment by Arcanemagus** [comment]
Waiting another day or two to release this as it is a somewhat large change.

**Comment by Arcanemagus** [comment]
No more feedback, merging and releasing and then it will start flooding in 😛.

**Pull request merged**
