### PR TITLE
Ensure fs.normalize() applied to exec path.

### PR DESCRIPTION
**Pull request by lexicalunit**
Fixes a small regression since addition of `applySubstitutions()` method.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Anyway to put in a spec to test for this?

**Comment by lexicalunit** [comment]
Good idea! I'll update this PR...

**Comment by lexicalunit** [comment]
Test added, checks that `"/path/to/fixtures/../fixtures/flake8"` gets normalized to `"/path/to/fixtures/flake8"`.

**Comment by Arcanemagus** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
Published in v1.12.1. :tada:

**Pull request merged**
