### PR TITLE
New flake8 shows full module path for F401, Fixes #211

### LINKED ISSUE #211: Import-errors on lines that don't exist at the bottom of the file instead of the top?
l618

Pictured is the last line of the file, L617. Note that it's calling out an import error from the top of the file on L618 which does not exist.

I could swear this started when I was briefly experimenting with an `isort` atom plug-in which I've since uninstalled.

Any ideas?

### PR DESCRIPTION
**Pull request by hvdklauw**
This change will split on . and take the last part, should still work for old flake8 users.

### CODE REVIEW

**Comment by djch** [comment]
I'd love to see this one merged sooner rather than later 😁

**Comment by Arcanemagus** [comment]
@hvdklauw Sorry for not getting to this sooner, can you fix the lint issues CI is complaining about?

**Comment by hvdklauw** [comment]
Yes, I'll have a look tomorrow!

**Comment by Arcanemagus** [comment]
Awesome, sorry about the incredibly long delay, lost this in my notifications and only just saw it looking at the list of PRs again.

**Comment by hvdklauw** [comment]
Fixed the error (not the warning, that was already there).

**Comment by Arcanemagus** [comment]
Looks like this got lost in the Travis-CI API downtime, trying to close/reopen to trigger the build.

**Comment by Arcanemagus** [comment]
Looks like the CI build passed and I just forgot to check back, sorry!

**Comment by Arcanemagus** [comment]
Odd, there are no conflicts merging this locally, not sure why GH thinks it can't me merged without attention...

**Comment by Arcanemagus** [comment]
Published in v1.13.3 🎉

**Pull request merged**
