### PR TITLE
Upgrade to the latest API

### LINKED ISSUE #50: Object.activate is deprecated.
Got this from Atom deprecation warning:

AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
Object.activate (/home/jborg/.atom/packages/Linter/lib/main.coffee:57:8)
Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
<unknown> (/usr/share/atom/resources/app.asar/src/package.js:221:30)
Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
```

### LINKED ISSUE #53: LinterRubocop.Linter is deprecated.
AtomLinter v0.X.Y API has been deprecated. Please refer to the Linter docs to update and the latest API: https://github.com/AtomLinter/Linter/wiki/Migrating-to-the-new-API
```
LinterFlake8.Linter (/Users/artur/.atom/packages/linter/lib/linter.coffee:60:4)
new LinterFlake8 (/Users/artur/.atom/packages/linter-flake8/lib/linter-flake8.coffee:25:4)
Object.lint (/Users/artur/.atom/packages/linter/lib/legacy.coffee:61:21)
<unknown> (/Users/artur/.atom/packages/linter/lib/editor-linter.coffee:69:25)
currentLinter (/Users/artur/.atom/packages/linter/lib/editor-linter.coffee:68:19)
<unknown> (/Users/artur/.atom/packages/linter/lib/editor-linter.coffee:82:22)
```

### PR DESCRIPTION
**Pull request by steelbrain**
Just like the title says
Fixes #53 
Fixes #50

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-flake8/56)

### CODE REVIEW

**Comment by steelbrain** [comment]
Ready to be used people

**Comment by badray** [comment]
@steelbrain nice :). I'll test is for a while, then release.

**Comment by ChaoticMind** [comment]
Shouldn't init.coffee be removed?

**Comment by steelbrain** [comment]
@ChaoticMind thanks! updated.

**Comment by ChaoticMind** [comment]
I have some questions/comments, if you don't mind: 
- What is the reasoning behind merging `init.coffee` and `linter-flake8.coffee` into `main.coffee`?
- Can we get some more whitespace in `main.coffee`? In this state, I find it incredibly unapproachable and hard to read. The old code was really good in that respect.
- I also find it hard to see what's changed in this PR since it both merges two files into one as well as modify their content, and not in separate commits, either (but just in 6cb5eb1c :(). But that's just me, and it's obviously fine as long as @badray keeps track of what's going on. This is more of a "in the future, it would be nice if..." kind of comment.

**Comment by steelbrain** [comment]
@ChaoticMind about point 1, It's because it didn't make any sense to keep it in separate files, in the previous version of linter, the API disallowed keeping stuff compact as required a file relative to the package name in the lib dir.
About Point 2, It's actually my personal taste, but if this package's maintainer suggests some whitespaces, I am happy and all to accept it.
About Point 3, I use commits like a snapshot feature, you commit a change that can work isolated, once you do, You can focus on doing the next parts of it as the previously entered content hides from the diff. It, again, is a personal taste thing, and I don't think of it as a bad thing, 'cause If you want to look at a full-overview then you can always view the diff, having small, specific commits makes development easier IMO.

**Comment by Arcanemagus** [comment]
@ChaoticMind Just a note on point 3, often with these linter updates it seems they are more "complete re-writes" as several things are no longer necessary and the structure of how they work has completely changed. It's possible to keep most of the old code and make it work (See [this linter](https://github.com/AtomLinter/linter-crystal) for an example), but it's usually simpler to re-write most of it.

As such, you can either split the "diffs" translating to completely different files into multiple commits that make very little sense, or just do one commit that replaces the entire content and makes it obvious the change.

That's been my experience "updating" 3 of them so far at least.

**Comment by ChaoticMind** [comment]
Cool, thanks for the info! (and for your work)

**Comment by ezarowny** [comment]
Much appreciated!

**Comment by badray** [comment]
@steelbrain Hi, sorry for long review - I'am on holidays right now.

1. Just like @ChaoticMind said - could you add vertical spaces for main.coffe :)? If you want I can do this as well.
2. Have you tested plugin? I can get it work with latest `Atom` and `AtomLinter`. With some weak debugging, I just saw that `provideLinters()` is not called - other linter plugin are working well. If plugin works for you, I'll try to debug more precisly...

**Comment by steelbrain** [comment]
@badray Sorry this took so much time, been busy lately.
I've added the vertical spaces and Yes, I am on the latest version of atom and it works flawlessly for me. Not sure what the problem is on your side.

**Comment by Arcanemagus** [comment]
The legacy API has been removed completely in v1.3.0 of `linter`, please review and merge this ASAP! :cry:

**Comment by Arcanemagus** [comment]
Tested the current state on my machine, it should catch everything with the new regex.

**Comment by Arcanemagus** [comment]
@badray can you test again? There was a bug in the old regex that caused it to only catch SyntaxError messages, that might be why it wasn't working for you?

**Comment by badray** [comment]
@Arcanemagus yes that was that. 

Sorry for such a slow reaction, I was on holidays :). Release imminent!

**Comment by Arcanemagus** [comment]
Thanks for getting this in!

**Pull request merged**
