### PR TITLE
Add options to adjust what are linter errors and warnings

### PR DESCRIPTION
**Pull request by eteq**
This PR adds check boxes that provide option to make all of the PEP8 "errors" (E* codes) into linter *warnings*, as well as flake "F* codes" into linter *errors*.

The motivation is that, in my view, all of the "errors" PEP8 yields should be thought of as suggestions.  After all, there's a whole section in PEP8 called ["A Foolish Consistency is the Hobgoblin of Little Minds"](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)... And I prefer my "errors" with the bright red dot to be real errors.  Of course others might think differently, so that's why this PR makes these an *option* (and leaves the defaults as they are right now).

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Can you add some specs to verify that it's working as intended?

**Comment by eteq** [comment]
Hmm... I think I can, @Arcanemagus, but one thing I'm not sure about: how do I set configuration options in a spec file without them affecting the "real" configuration?  (Sorry if it's a silly question - I haven't really used Jasmine or spec files before...)

**Comment by Arcanemagus** [comment]
I think specs run on a blank config, I know they at least don't access current settings, so you should be safe just using `atom.config.set()`. If you are worried though you could always use `atom.config.get()` to get the current value, then `set()` to set it to what you want, then `set()` again to change it back.

Specs aren't really meant to be run by end users though so I'm not sure how much of a concern that should be, none of the other `linter-*` plugins take this into account.

**Comment by eteq** [comment]
OK, I think those commits should do it, @Arcanemagus .  I just tried it now and it looks like you're right that it doesn't affect the current settings - thanks for the tip!

**Comment by Arcanemagus** [comment]
LGTM, thanks!

**Comment by Arcanemagus** [comment]
Published in v1.10.0.

**Pull request merged**
