### PR TITLE
Added "g" flag to project path replacement

### LINKED ISSUE #290: Multiple $PROJECT not work
Hi,

I hope someone can read my Engrish :)

Using multiple $PROJECT to executable path, `$PROJECT` keywords are not replaced with the path of the project, except the path specified at first. For example, putting the following paths

```$PROJECT/../bin/flake8;$PROJECT/bin/flake8;$PROJECT/venv/bin/flake8;$PROJECT/.venv/bin/flake8;$PROJECT/env/bin/flake8;$PROJECT/.env/bin/flake8;/usr/bin/flake8```

and if `$PROJECT` is `/User/hyamamoto/Documents/Workspace/test`, replacing all `$PROJECT` with `/User/hyamamoto/Documents/Workspace/test` is expected, but it doesn't. Instead I could see

```
/User/hyamamoto/Documents/Workspace/bin/flake8;$PROJECT/bin/flake8;$PROJECT/venv/bin/flake8;$PROJECT/.venv/bin/flake8;$PROJECT/env/bin/flake8;$PROJECT/.env/bin/flake8;/usr/bin/flake8
```

Additionaly, as far as I checked the code, [this] should be this imo:

```Javascript
const applySubstitutions = (givenExecPath, projDir) => {
  let execPath = givenExecPath;
  const projectName = path.basename(projDir);
  execPath = execPath.replace(/\$PROJECT_NAME/ig, projectName); // Added "g" modifier
  execPath = execPath.replace(/\$PROJECT/ig, projDir); // Added "g" modifier
  const paths = execPath.split(';');
  for (let i = 0; i < paths.length; i += 1) {
    if (fs.existsSync(paths[i])) {
      return paths[i];
    }
  }
  return execPath;
};
```

Thanks

[this]: https://github.com/AtomLinter/linter-flake8/blob/b31657b8aa9df6b9797335fe7b4a79f4b62f1656/lib/main.js#L65

### PR DESCRIPTION
**Pull request by hiroaki-yamamoto**
Hi,
I found multiple `$PROJECT` and `$PROJECT_NAME` were not replaced properly and this PR fixes the issue.

Edit (by @Arcanemagus):
Fixes #290.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Can you please add a spec testing this?

**Comment by hiroaki-yamamoto** [comment]
Done, but sorry, I created a new file that is named "utils.js" to test the replacement function.

**Comment by Arcanemagus** [comment]
I meant adding a test like [this one](https://github.com/AtomLinter/linter-flake8/blob/2a4c05a7d633f0315934758dbdf63c1479697fd2/spec/linter-flake8-spec.js#L192-L201), but with multiple replacements 😕. As far as I can tell your new specs are just duplicating the existing ones for the most part.

Also I'd much prefer _not_ creating a new file for a 2 line function, especially since what it does is already being tested in the `executable path` section.

**Comment by hiroaki-yamamoto** [comment]
Done.

**Comment by Arcanemagus** [comment]
Much cleaner, thanks for sticking through with this!

**Pull request merged**
