### PR TITLE
change lintOnFly to true

### PR DESCRIPTION
**Pull request by Ryex**
change lintOnFly to true as per issue #61

### CODE REVIEW

**Comment by steelbrain** [comment]
LGTM.

**Comment by badray** [comment]
@steelbrain i thought that would be better if plugin will inherit this setting from linter package... ?

**Comment by steelbrain** [comment]
@badray It already inherits settings from the linter package, if lintOnFly is disabled there, it's disabled everywhere.

**Comment by badray** [comment]
@steelbrain Ok, good. But I'm not happy with currect release of `1.6.1` :( because I was planownik to fix couple bugs before 1.6.1 release - as i stated in couple issues in this repo.

I know that my responses are not very fast, but please inform me of any planned releases.

**Comment by steelbrain** [comment]
Ouch, sorry. I thought this change would be a minor + benefitting to a lot of users.

**Comment by badray** [comment]
@steelbrain No problem - just poke me next time before release :).

**Pull request merged**
